repos:
- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.0.1
  hooks:
    - id: add-trailing-comma

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: trailing-whitespace

- repo: https://gitlab.com/pycqa/flake8
  rev: master
  hooks:
    - id: flake8
